//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyHours.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FACULTY_ASSIGNMENT
    {
        public int ID { get; set; }
        public int FacultyID { get; set; }
        public int StudentGroupID { get; set; }
        public int TeacherID { get; set; }
    
        public virtual FACULTY FACULTY { get; set; }
        public virtual STUDENT_GROUP STUDENT_GROUP { get; set; }
        public virtual TEACHER TEACHER { get; set; }
    }
}
