//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyHours.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAJOR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MAJOR()
        {
            this.SPECIALITY = new HashSet<SPECIALITY>();
            this.SPECIALITY_MAJOR_ASSIGNMENT = new HashSet<SPECIALITY_MAJOR_ASSIGNMENT>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public int FacultyID { get; set; }
    
        public virtual FACULTY FACULTY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SPECIALITY> SPECIALITY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SPECIALITY_MAJOR_ASSIGNMENT> SPECIALITY_MAJOR_ASSIGNMENT { get; set; }
    }
}
