//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyHours.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SPECIALITY_MAJOR_ASSIGNMENT
    {
        public int ID { get; set; }
        public int MajorID { get; set; }
        public int SpecialityID { get; set; }
    
        public virtual MAJOR MAJOR { get; set; }
    }
}
