//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyHours.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUBJECT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SUBJECT()
        {
            this.SUBJECT_ASSIGNMENT = new HashSet<SUBJECT_ASSIGNMENT>();
            this.SUBJECT_ASSIGNMENT_TEMP = new HashSet<SUBJECT_ASSIGNMENT_TEMP>();
        }
    
        public int ID { get; set; }
        public string SubjectCode { get; set; }
        public string Name { get; set; }
        public string Language { get; set; }
        public int SpecialityID { get; set; }
        public int NumberOfGroups { get; set; }
        public int AssignedHours { get; set; }
        public int UsedHours { get; set; }
        public int LabHours { get; set; }
        public int LecHours { get; set; }
        public int SemHours { get; set; }
        public int PrjHours { get; set; }
        public int ExcHours { get; set; }
        public int DipHours { get; set; }
    
        public virtual SPECIALITY SPECIALITY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SUBJECT_ASSIGNMENT> SUBJECT_ASSIGNMENT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SUBJECT_ASSIGNMENT_TEMP> SUBJECT_ASSIGNMENT_TEMP { get; set; }
    }
}
