//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyHours.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class SUBJECT_ASSIGNMENT
    {
        public int ID { get; set; }
        [Range(0,100)]
        public int Hours { get; set; }
        [Range(0,10)]
        public int Semester { get; set; }
        public int TeacherID { get; set; }
        public bool IsSubstitute { get; set; }
        public string IsSubstituteDescription { get; set; }
        public int StudentGroupID { get; set; }
        public int SubjectID { get; set; }
        public int SubjectTypeID { get; set; }
        public int StudiesTypeID { get; set; }
    
        public virtual STUDENT_GROUP STUDENT_GROUP { get; set; }
        public virtual STUDIES_TYPE_DICT STUDIES_TYPE_DICT { get; set; }
        public virtual SUBJECT SUBJECT { get; set; }
        public virtual SUBJECT_TYPE_DICT SUBJECT_TYPE_DICT { get; set; }
        public virtual TEACHER TEACHER { get; set; }
    }
}
