//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyHours.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string FirstName { get; set; }
        public string SecondName { get; set; }
        public string PhoneNumber { get; set; }
        public int UserTypeID { get; set; }
        public int TeacherID { get; set; }
        public string AspNetUserID { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual TEACHER TEACHER { get; set; }
        public virtual USER_TYPE USER_TYPE { get; set; }
    }
}
